module.exports = {
  overrides: [
    {
      files: ['package.json'],
      parser: 'jsonc-eslint-parser',
      rules: {
        'jsonc/array-bracket-newline': [
          'error',
          {
            multiline: true,
            minItems: 0,
          },
        ],
        'jsonc/array-element-newline': ['error', 'always'],
        'jsonc/object-curly-newline': ['error', 'always'],
        'jsonc/object-property-newline': 'error',
        'jsonc/sort-array-values': ['error', {
          pathPattern: '^files$',
          order: [
            { valuePattern: 'index.*' },
            { valuePattern: 'main.*' },
            { order: { type: 'asc' } },
          ],
        }],
        'jsonc/sort-keys': [
          'warn',
          {
            pathPattern: '^$',
            order: [
              'name',
              'private',
              'version',
              'author',
              'contributors',
              'maintainers',
              'keywords',
              'description',
              'license',
              'homepage',
              'repository',
              'bugs',
              'publishConfig',
              'funding',
              'packageManager',
              'workspaces',
              'engines',
              'type',
              'files',
              'exports',
              'main',
              'module',
              'unpkg',
              'bin',
              'scripts',
              'gitHooks',
              'husky',
              'simple-git-hooks',
              'lint-staged',
              'peerDependencies',
              'peerDependenciesMeta',
              'bundledDependencies',
              'dependencies',
              'optionalDependencies',
              'devDependencies',
              'resolutions',
              'overrides',
              'changelog',
              'config',
              'browserLists',
              'prettier',
              'eslintIgnore',
              'eslintConfig',
              'stylelint',
              'jest',
            ],
          },
          {
            pathPattern: '^(?:(?:dev|peer|optional|bundled)?[Dd]ependencies|resolutions|overrides)$',
            order: { type: 'asc' },
          },
          {
            pathPattern: '^scripts$',
            order: [
              'prepare',
              'prepack',
              'postpack',
              'publish',
              'prepublishOnly',
              'postpublish',
              'preinstall',
              'install',
              'postinstall',
              'preuninstall',
              'uninstall',
              'postuninstall',
              'preversion',
              'version',
              'postversion',
              'prestart',
              {
                keyPattern: '^start',
              },
              'poststart',
              'prerestart',
              {
                keyPattern: '^restart',
              },
              'postrestart',
              'prestop',
              {
                keyPattern: '^stop',
              },
              'poststop',
              'dev',
              'prebuild',
              {
                keyPattern: '^build',
              },
              'postbuild',
              'serve',
              'preview',
              'pretest',
              {
                keyPattern: '^test',
              },
              'posttest',
              {
                keyPattern: '^lint',
              },
            ],
          },
          {
            pathPattern: '^(?:gitHooks|husky|simple-git-hooks)$',
            order: [
              // client hooks only
              'pre-commit',
              'prepare-commit-msg',
              'commit-msg',
              'post-commit',
              'pre-rebase',
              'post-rewrite',
              'post-checkout',
              'post-merge',
              'pre-push',
              'pre-auto-gc',
            ],
          },
          {
            pathPattern: '^eslintConfig$',
            order: [
              'root',
              'env',
              'globals',
              'settings',
              'parser',
              'parserOptions',
              'extends',
              'plugins',
              'processor',
              'noInlineConfig',
              'ignorePatterns',
              'rules',
              'overrides',
            ],
          },
          {
            pathPattern: '^stylelint$',
            order: [
              'extends',
              'plugins',
              'processors',
              'defaultSeverity',
              'ignoreFiles',
              'ignoreDisables',
              'customSyntax',
              'reportNeedlessDisables',
              'reportInvalidScopeDisables',
              'reportDescriptionlessDisables',
              'rules',
              'overrides',
            ],
          },
        ],
      },
    },
  ],
}
