module.exports = {
  overrides: [
    {
      files: ['package.json'],
      parser: 'jsonc-eslint-parser',
      rules: {
        'jsonc/array-bracket-newline': [
          'error',
          {
            multiline: true,
            minItems: 0,
          },
        ],
        'jsonc/array-element-newline': ['error', 'always'],
        'jsonc/object-curly-newline': ['error', 'always'],
        'jsonc/object-property-newline': 'error',
        'jsonc/sort-array-values': ['error', {
          pathPattern: '^files$',
          order: [
            { valuePattern: 'index.*' },
            { valuePattern: 'main.*' },
            { order: { type: 'asc' } },
          ],
        }],
        'jsonc/sort-keys': [
          'warn',
          {
            pathPattern: '^$',
            order: [
              'name',
              'author',
              'private',
              'version',
              'description',
              'keywords',
              'license',
              'repository',
              'bugs',
              'publishConfig',
              'funding',
              'packageManager',
              'workspaces',
              'engines',
              'type',
              'files',
              'exports',
              'main',
              'module',
              'unpkg',
              'bin',
              'scripts',
              'gitHooks',
              'husky',
              'simple-git-hooks',
              'lint-staged',
              'peerDependencies',
              'peerDependenciesMeta',
              'bundledDependencies',
              'dependencies',
              'optionalDependencies',
              'devDependencies',
              'changelog',
              'prettier',
              'eslintConfig',
              'jest',
            ],
          },
          {
            pathPattern: '^(?:dev|peer|optional|bundled)?[Dd]ependencies$',
            order: { type: 'asc' },
          },
        ],
      },
    },
  ],
}
