name: Node.js Package
# master push
on:
  push:
    branches: [ 'master' ]
    paths-ignore:
      - "**/*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: | 
          git config --global user.email "noreply@github.com"
          git config --global user.name "github-actions"
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"

      - run: yarn bootstrap
      - run: yarn release --no-verify-access
