name: Node.js Package
# master push
on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm config set registry https://registry.npmjs.org
        npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
    - run: | 
        git config --global user.email "mutoe@foxmail.com"
        git config --global user.name "mutoe"

    - run: yarn bootstrap
    - run: yarn release
