name: Node.js Package
# master push
on:
  push:
    branches: [ 'master' ]
    tags: [ 'v*' ]
    paths-ignore:
      - "**/*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: | 
          git config --global user.email "noreply@github.com"
          git config --global user.name "github-actions"
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"

      - run: pnpm bootstrap
      - run: pnpm release --no-verify-access
